<script>
require([
    'jquery',
    'Magento_Ui/js/modal/confirm'
],
function($, confirmation) {
    $('body').on('click', '.adminPassword', function(e) {    
        e.preventDefault();
        $('.updatepasswordtextbox').css('border-color','#adada');
        let valId = $(this).data('value');
        let textValue = $('#textbox-'+valId).val();

        $('#msg-'+valId).html('');
        if(!textValue)
        {
            $('#textbox-'+valId).css('border-color','#FF0000');
            $('#msg-'+valId).html('Password Required!');
            return false;
        }

        confirmation({
            title: 'Update Password',
            content: 'Do you want to update password for this customer?',
            actions: {

                confirm: function () {
                    $('#msg-'+valId).html('Updating...');
                    $.ajax({
                         showLoader: true,
                         url: '<?php  echo $this->getUrl("passwordupdate/customer/update");?>',
                         data: {valId:valId,textValue:textValue},
                         type: "POST",
                         success: function (data) {
                            $('#msg-'+valId).html('Updated');
                            setTimeout(
                            function() 
                            {
                                $('#msg-'+valId).html('');
                                $('#textbox-'+valId).val('');
                            }, 3000);
                             <!-- things you want to perform on success or you can reload the page to show changes -->
                         },
                         error: function (error) {
                            $('#msg-'+valId).html('Someting Wrong!');
                            setTimeout(
                            function() 
                            {
                                $('#msg-'+valId).html('');
                                $('#textbox-'+valId).val('');
                            }, 3000);
                         }
                    });
                },

                cancel: function () {
                    return false;
                }
            }
        });
    });
});
</script>